# version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ushort
      - DB_PASSWORD=randompassword
      - DB_NAME=ushort
      - DB_SSLMODE=disable
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - ushort-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ushort
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=ushort
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ushort-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ushort-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ushort.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ushort-network

volumes:
  postgres-data:
  redis-data:

networks:
  ushort-network:
    driver: bridge
